### ISSUE TITLE
关于云梯项目咨询

### ISSUE THREAD

**Issue by xqgithub** [zhgqthomas/ladder#1]
我在看你写的这个项目，遇到点小问题。
1.我下载你这个项目是可以跑起来的，在网上找了ISS的连接地址，是可以科学上网的。
2.但是现在遇到一个问题就是，我在那个原作者【madeye 】那里打包的编译了SO文件，放在你的程序是无法运行的，我猜测是Jni里面的文件发生的变化。
3.我想问的是您当时写这个项目的时候 是参照 那个【scala】版本的吗？如果可以的话能不能加个联系方式，我有些问题想问下您。

**Comment by zhgqthomas** [comment]
@xqgithub 这个项目 c 层的代码确实是参考的 scala 那个版本，但是我参考的是比较老的版本，你用现在他的版本编译出来的 so 文件直接放到这个项目里肯定是跑不通的，你如果熟悉了他的那个版本可以在这个版本进行修改应该就可以跑通了

**Comment by zhgqthomas** [comment]
@xqgithub 923877979 这是我的 qq 号
